# We use "hosts: all" as terraform passes ansible a list of exactly one host
- hosts: all
  #gather_facts: true # https://github.com/zzet/ansible-rbenv-role/issues/37
  become: true  # super user required for most tasks


####################### Variables ######################################################
  vars:
    appname: 'sinatra'


####################### BEGIN BUILD ######################################################
  pre_tasks:
    - name: Set timezone to Australia/Melbourne
      timezone:
        name: Australia/Melbourne



####################### Packages #######################################################
    - name: Update all packages to the latest version
      environment: 
        DEBIAN_FRONTEND: 'noninteractive'
      apt:
        update_cache: yes
        upgrade: dist

    - name: Ensure build deps are installed
      environment: 
        DEBIAN_FRONTEND: 'noninteractive'
      apt:
        install_recommends: no
        name: "{{ packages }}"
      vars:
        packages:
        - apt-transport-https
        - ruby2.7
        - fail2ban

    ############ Deploy Sinatra Application ######


    ############ Configure fail2ban ##############
    # - name: Tweak fail2ban to catch ssh preauth failures
    #   copy:
    #     src: fail2ban-sshd.conf
    #     dest: /etc/fail2ban/filter.d/sshd.conf

    # Reboot 
    - name: Reboot to apply any system/security updates
      reboot:
        reboot_timeout: 120